############################
#Television ratings api built with an api gateway frontend as a lambda proxy
#
#1) Runs the cloudformation template to create dev environment
#
#
############################
version: 0.2

phases:
  ###########################################
  #Uses a python runtime
  #Note that you do not need the \ to escape
  #aws cli commands
  ###########################################
  install:
    runtime-versions:
       python: 3.8

    commands:
      - echo Entered the install phase...
      - BUILD_ENVIRONMENT=dev-ratingsapi
      - APIGW_STACK="${BUILD_ENVIRONMENT}-apigw"     
      - pip install -r tests/requirements_dev.txt
  build:
    commands:
      - echo Defined build variables
      - echo $BUILD_ENVIRONMENT
      - echo $APIGW_STACK



      
      - echo "Creating $APIGW_STACK"
      - aws cloudformation create-stack --stack-name $APIGW_STACK
          --template-body file://templates/api_s3_bucket.yml

      #Waits until the stack has been successfully created
      - aws cloudformation wait stack-create-complete
        --stack-name $APIGW_STACK


      # - aws cloudformation create-stack --stack-name $APIGW_STACK
      #     --template-body file://templates/api_s3_bucket.yml
      #     --capabilities CAPABILITY_NAMED_IAM

      # - aws s3 cp templates/openapi3_spec.yml "s3://${BUILD_ENVIRONMENT}/v1"

      # #Waits until the stack has been successfully created
      # - aws cloudformation wait stack-create-complete
      #   --stack-name $APIGW_STACK

      #run tests after stack has built
      - python -m unittest tests.test_dev_aws_resources 


  post_build:
    commands:
      - echo cleaning up resources

      - aws cloudformation delete-stack --stack-name $APIGW_STACK


artifacts:
  files:
    ##########################
    #Adds artifact that can be referenced in later stages from 
    #${CODEBUILD_SRC_DIR_BuildDevratingsapi}
    ##########################
    - 'logs/*'
  name: 'BuildDevratingsapi'
