############################
#Television ratings api built with an api gateway frontend as a lambda proxy
#
#1) Runs the cloudformation template to create dev environment
#
#
############################
version: 0.2

phases:
  ###########################################
  #Uses a python runtime
  #Note that you do not need the \ to escape
  #aws cli commands
  ###########################################
  install:
    runtime-versions:
       python: 3.8

    commands:
      - echo Entered the install phase...
      - BUILD_ENVIRONMENT=dev-ratingsapi
      - HTTP_API_STACK="${BUILD_ENVIRONMENT}-http-apigw"
      - S3_DEPENDENCY_STACK="${BUILD_ENVIRONMENT}-s3-dependency"      
      - pip install -r tests/requirements_dev.txt
  build:
    commands:
      - echo Defined build variables
      - echo $BUILD_ENVIRONMENT
      - echo $S3_DEPENDENCY_STACK
      - echo $HTTP_API_STACK
      - echo $S3_DEPENDENCY_STACK


      
      - echo "Creating $S3_DEPENDENCY_STACK"
      - aws cloudformation create-stack --stack-name $S3_DEPENDENCY_STACK
          --template-body file://templates/api_s3_bucket.yml

      #Waits until the stack has been successfully created
      - aws cloudformation wait stack-create-complete
        --stack-name $S3_DEPENDENCY_STACK


      #run tests after stack has built
      - python -m unittest tests.test_dev_aws_resources


  post_build:
    commands:
      - echo cleaning up resources

      # - aws cloudformation delete-stack --stack-name $S3_DEPENDENCY_STACK


artifacts:
  files:
    ##########################
    #Adds artifact that can be referenced in later stages from 
    #${CODEBUILD_SRC_DIR_BuildDevratingsapi}
    ##########################
    - 'logs/*'
  name: 'BuildDevratingsapi'
