############################
#Prod deployment
#
#Merges dev branch into master branch for
#ratingsapi
############################
version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.8
    commands:
      - echo Entered the install phase...

      - APIGW_STACK="${BUILD_ENVIRONMENT}-${PROJECT_NAME}-apigw" 
      - BUILD_ENVIRONMENT=prod
      - PROJECT_NAME=ratingsapi
      - pip install -r tests/requirements_prod.txt
      - ls -l
    finally:

  build:
    commands:
      - echo Defined build variables
      - echo $BUILD_ENVIRONMENT
      - echo $PROJECT_NAME

      - echo "Iterating lambda functions"
      - ./builds/iterate_lambda.sh

      #rest api id for creating a deployment
      - REST_API_ID=$(aws cloudformation describe-stacks --query
        "Stacks[0].Outputs[?OutputKey=='ratingsApigatewayId'].OutputValue"
        --stack-name $APIGW_STACK --output text)

      - echo $REST_API_ID

      #runs prod tests
      - python -m unittest tests.test_aws_resources

      #merges dev branch into master now that all tests have
      #been passed and artifacts created
      - aws codecommit merge-branches-by-fast-forward
        --source-commit-specifier dev
        --destination-commit-specifier master
        --repository-name $PROJECT_NAME

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

