---
AWSTemplateFormatVersion: '2010-09-09'

#Transforms any serverless code to cloudformation
Transform: AWS::Serverless-2016-10-31

Description:
  'Television ratings api built with an api gateway frontend as a lambda proxy'

Parameters:

  apiStageName:
    Type: String
    Default: 'v1'   

  dynamoDbTableName:
    Type: String
    Default: 'prod_toonami_ratings'
    Description: Name of the dynamodb table

  environPrefix:
    Type: String
    Default: dev
    Description: String for prefixing resources to differentiate prod/dev


  projectName:
    Type: String
    Default: 'ratingsapi'
    Description: Name of the project


Conditions: 
  prodConfiguration: !Equals [ !Ref environPrefix, prod ]

Resources:

  #service linked role for apigateway to write to cloudwatch logs
  #for the account
  apigwToCwLogsServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  #account setup for CW logs
  restApiCwLogs:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt apigwToCwLogsServiceRole.Arn


  ratingsApiGw:
    Type: AWS::ApiGateway::RestApi
    Properties:
      #if we are deploying to prod we use EDGE, otherwise 
      #we use a regional endpoint
      EndpointConfiguration:
        Types:
          - !If [prodConfiguration, 'EDGE', 'REGIONAL']
      Name: !Sub '${projectName}-${environPrefix}'
      Description: API used for television ratings
      Tags:
          -
            Key: keep
            Value: 'yes'
          -
            Key: source
            Value: !Ref projectName


  ratingsV1Deployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn: ratingsShowProxyMethod
    Properties:
      RestApiId: !Ref ratingsApiGw
      Description: Single stage deployment
      StageDescription:
        DataTraceEnabled: True
        LoggingLevel: INFO
        TracingEnabled: True
        Tags:
            -
              Key: keep
              Value: 'yes'
            -
              Key: source
              Value: !Ref projectName
      StageName: !Ref apiStageName


  ratingsUsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    DependsOn: ratingsV1Deployment
    Properties:
      ApiStages:
        - ApiId: !Ref ratingsApiGw
          Stage: !Ref apiStageName
      Description: Generic Usage plan
      Quota:
        Limit: 1000
        Period: MONTH
      Throttle:
        BurstLimit: 200
        RateLimit: 100
      UsagePlanName: all_clients

  # apiGatewayInvokeLambda:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               - apigateway.amazonaws.com
  #               - lambda.amazonaws.com
  #           Action:
  #             - sts:AssumeRole
  #     Policies:
  #       - PolicyName: !Sub '${projectName}LambdaPolicy'
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:
  #             - Sid: LambdaAccess
  #               Effect: Allow
  #               Action:
  #                 - lambda:InvokeFunction
  #                 - lambda:GetFunctionConfiguration
  #               Resource: '*'
  #                 #- !GetAtt 'LambdaFunction.Arn'


  #########################
  #Individual path resources/parameters with their lambda proxies
  #########################

  ratingsShowsResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ratingsApiGw
      ParentId: !GetAtt ratingsApiGw.RootResourceId
      PathPart: 'shows'

  ratingsShowsProxyResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ratingsApiGw
      ParentId: !Ref ratingsShowsResource
      PathPart: '{show}'

  ####################################################
  #Docs for giving api gateway permission to invoke a lambda function
  #https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html#apigateway-permissions
  ####################################################
  ratingsShowPermission: 
    Type: AWS::Lambda::Permission 
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt showsEndpoint.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join [ '', [!Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:',
        !Ref ratingsApiGw, '/*/GET/*']]

  ratingsShowProxyMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      ApiKeyRequired: True
      RestApiId: !Ref ratingsApiGw
      ResourceId: !Ref ratingsShowsProxyResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${showsEndpoint.Arn}/invocations



  showsEndpoint:
    Type: AWS::Serverless::Function
    Properties:                               
      Description: |
        Lambda function to handle shows endpoint
      #passed to os.environ for python used to
      #determine which table to update in scripts.reddit_ratings.main
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref dynamoDbTableName

      FunctionName: !Sub '${projectName}-shows-endpoint-${environPrefix}'
      Handler: index.handler

      #Policies to include in the lambda basic execution role
      #created by SAM
      Policies:
        Version: '2012-10-17'
        Statement: 
          #dynamodb permissions     
          - Sid: !Sub '${projectName}LambdaDynamoDbAllow'
            Effect: Allow
            Action:
              - dynamodb:ListTables
              - dynamodb:GetItem
              - dynamodb:Query

            Resource:
              - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${dynamoDbTableName}'  
              - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${dynamoDbTableName}/index/SHOW_ACCESS'     
              - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${dynamoDbTableName}/index/YEAR_ACCESS'
      Runtime: python3.7
      Tracing: Active
      #60 second timeout
      Timeout: 5
      #Default code that will be updated by
      #CodeBuild Job
      InlineCode: |
        def handler(event, context):
          print("Hello, world!")
    Tags:
      -
        Key: keep
        Value: 'yes'
      -
        Key: source
        Value: !Ref projectName


  ratingsYearsResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ratingsApiGw
      ParentId: !GetAtt ratingsApiGw.RootResourceId
      PathPart: 'years'

  ratingsYearProxyResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ratingsApiGw
      ParentId: !Ref ratingsYearsResource
      PathPart: '{year}'



Outputs:
  ratingsApigatewayId:
    Value: !Ref ratingsApiGw