---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  'Television ratings api built with an api gateway frontend as a lambda proxy'

Parameters:
  ProjectName:
    Type: String
    Default: 'ratingsapi'
    Description: Simple S3 Bucket Example

  EnvironPrefix:
    Type: String
    Default: dev
    Description: String for prefixing resources to differentiate prod/dev


Resources:
  RatingsHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      BodyS3Location: 
        Bucket: !Sub '${EnvironPrefix}-${ProjectName}-openapi-dependency'
        Key: v1/openapi3_spec.yml
      #Target: arn:aws:apigateway:{region}:lambda:path/2015-03-31/functions/arn:aws:lambda:{region}:{account-id}:function:{function-name}/invocations
